update leaflet and mapbox version
sitcomlab/Ethermap pull request #1
Opened 2021-09-07 12:48 UTC by PaulaScharf

This fixes watching the map bounds of other maps and enables touch interaction with the map.

2021-09-07 15:05 UTC, noerw requested changes

2021-09-07 15:05 UTC, noerw commented on package-lock.json
> +  "lockfileVersion": 1,
Changes to this file are unneccessary, please revert. It was created because you used an old npm version which does not support lockfile v2.
To avoid this, you can update npm, usually  running `npm install -g npm@latest` is enough.
https://docs.npmjs.com/try-the-latest-stable-version-of-npm

2021-09-07 15:05 UTC, noerw commented on app/views/index.html
> +  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css' />
While we're changing these, it would be nice to vendor these dependencies in this repo for enhanced privacy.
Would you mind downloading these assets and place them in a folder `app/thirdparty` or similar?

2021-09-07 15:05 UTC, noerw commented on app/scripts/leaflet/mapDirective.js
> +          L.mapbox.accessToken = 'pk.eyJ1Ijoic2l0Y29tbGFiIiwiYSI6ImNqNjd4a3pkdTA5ZmkyemxzNjBvZWQ0ZGcifQ.ctIXrv-GP4kWn7uMdt4yPQ';
It's not a great practice to hardcode secrets like that.
Though I think we can leave this as is, considering that we don't have any infrastructure in place for passing environment variables from backend to frontend yet (that might be a good future addition).

Is this your personal mapbox token? You can (and should) guard against misuse by enabling the domain allow list in the mapbox dashboard.

2021-09-15 11:07 UTC, PaulaScharf commented on app/scripts/leaflet/mapDirective.js
> +          L.mapbox.accessToken = 'pk.eyJ1Ijoic2l0Y29tbGFiIiwiYSI6ImNqNjd4a3pkdTA5ZmkyemxzNjBvZWQ0ZGcifQ.ctIXrv-GP4kWn7uMdt4yPQ';
Yes, you are right. This is not my token. I found this token in line 97 of the same file. I dont know who it belongs to.

2021-09-15 11:08 UTC, PaulaScharf commented on app/views/index.html
> +  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css' />
ok, I will look into that.

2021-09-15 11:09 UTC, PaulaScharf commented on package-lock.json
> +  "lockfileVersion": 1,
good catch, I will revert this

2021-09-15 13:00 UTC, PaulaScharf commented on app/scripts/leaflet/mapDirective.js
> +          L.mapbox.accessToken = 'pk.eyJ1Ijoic2l0Y29tbGFiIiwiYSI6ImNqNjd4a3pkdTA5ZmkyemxzNjBvZWQ0ZGcifQ.ctIXrv-GP4kWn7uMdt4yPQ';
Im gonna leave this as is for now

2021-09-15 13:51 UTC, noerw commented on app/scripts/leaflet/mapDirective.js
> +          L.mapbox.accessToken = 'pk.eyJ1Ijoic2l0Y29tbGFiIiwiYSI6ImNqNjd4a3pkdTA5ZmkyemxzNjBvZWQ0ZGcifQ.ctIXrv-GP4kWn7uMdt4yPQ';
Oh didn't see that, alright ;)

2021-09-15 13:54 UTC, noerw commented on app/thirdParty/googleRobotoFont-400-300-700.css
> +  src: url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmSU5fCRc4EsA.woff2) format('woff2');
Hmm, these fonts are still loaded from google. If I really need google fonts, I usually install https://www.npmjs.com/package/@fontsource/roboto
But integrating that into the built might be some effort (idk), so I'll merge this as is for now

2021-09-15 14:08 UTC, noerw commented
closing as per https://github.com/sitcomlab/Ethermap/pull/2#pullrequestreview-755172146

2021-09-15 14:08 UTC, closed without merging